name: picard_collecthsmetrics
description: Collects hybrid-selection (HS) metrics for a SAM or BAM file.
keywords:
  - collecthsmetrics
  - bam
  - sam
  - cram
tools:
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM file
      pattern: "*.{bam,cram,sam}"
  - fasta:
      type: file
      description: Reference genome fasta file
      pattern: "*.{fasta,fa}"
  - fai:
      type: file
      description: Reference genome fasta index
      pattern: "*.{fai}"
  - bait:
      type: file
      description: bait interval file in Picard interval_list format (bed)
      pattern: "*.{bed}"
  - target: 
      type: file
      description: target interval file in Picard interval_list format (bed)
      pattern: "*.{bed}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - metrics:
      type: file
      description: HS metrics file generated by picard
      pattern: "*.{metrics.txt}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@skillcoyne"
